//------------------------------------------------------------------------------
//  <auto-generated>
//  此代码由模板自动生成
//  文件名称:T_xiugai_log.cs
//  生成时间: 2016-10-28 08:52:00 by dlm
//  对此文件的更改可能会导致不正确的行为，并且如果
//  重新生成代码，这些更改将会丢失
//  </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq; 
using System.Text;
namespace Gozyy.CarMaint.Models 
{
        [Gozyy.Repositories.TableName("T_xiugai_log")]
		[Gozyy.Repositories.PrimaryKey("ID")]										
        public partial class T_xiugai_log
        {
            
		    /// <summary>
		    /// 
		    /// </summary>		
								    public int ID { get; set; }
					    
		    /// <summary>
		    /// 
		    /// </summary>		
						public string Xiangmuname { get; set; }
								    
		    /// <summary>
		    /// 
		    /// </summary>		
						public string time { get; set; }
								    
		    /// <summary>
		    /// 
		    /// </summary>		
						public string xiugainame { get; set; }
								    
		    /// <summary>
		    /// 
		    /// </summary>		
						public string beizhuinfor { get; set; }
								     
        } 
		public partial class T_xiugai_logValid
		{
			public static string Check(T_xiugai_log m)
			{
																
				if(m.Xiangmuname!=null && m.Xiangmuname.Length>100)
				{
					return "Xiangmuname过长(100)!";
				}
												
				if(m.time!=null && m.time.Length>50)
				{
					return "time过长(50)!";
				}
												
				if(m.xiugainame!=null && m.xiugainame.Length>50)
				{
					return "xiugainame过长(50)!";
				}
												
				if(m.beizhuinfor!=null && m.beizhuinfor.Length>16)
				{
					return "beizhuinfor过长(16)!";
				}
								 
				return "";
			}
		}
}
   