//------------------------------------------------------------------------------
//  <auto-generated>
//  此代码由模板自动生成
//  文件名称:Tbbolgs.cs
//  生成时间: 2016-12-29 14:09:42 by dlm
//  对此文件的更改可能会导致不正确的行为，并且如果
//  重新生成代码，这些更改将会丢失
//  </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq; 
using System.Text;
namespace Gozyy.ToolClass.Models 
{
        [Gozyy.Repositories.TableName("Tbbolgs")]
																		
        public partial class Tbbolgs
        {
            
		    /// <summary>
		    /// 
		    /// </summary>		
								    public int ID { get; set; }
					    
		    /// <summary>
		    /// 
		    /// </summary>		
						public string bolgname { get; set; }
								    
		    /// <summary>
		    /// 
		    /// </summary>		
						public string author { get; set; }
								    
		    /// <summary>
		    /// 
		    /// </summary>		
								    public DateTime? times { get; set; }
					    
		    /// <summary>
		    /// 
		    /// </summary>		
						public string article { get; set; }
								    
		    /// <summary>
		    /// 
		    /// </summary>		
						public string picture { get; set; }
								    
		    /// <summary>
		    /// 
		    /// </summary>		
						public string details { get; set; }
								    
		    /// <summary>
		    /// 
		    /// </summary>		
						public string states { get; set; }
								     
        } 
		public partial class TbbolgsValid
		{
			public static string Check(Tbbolgs m)
			{
																
				if(m.bolgname!=null && m.bolgname.Length>50)
				{
					return "bolgname过长(50)!";
				}
												
				if(m.author!=null && m.author.Length>20)
				{
					return "author过长(20)!";
				}
																				
				if(m.article!=null && m.article.Length>16)
				{
					return "article过长(16)!";
				}
												
				if(m.picture!=null && m.picture.Length>50)
				{
					return "picture过长(50)!";
				}
												
				if(m.details!=null && m.details.Length>50)
				{
					return "details过长(50)!";
				}
												
				if(m.states!=null && m.states.Length>50)
				{
					return "states过长(50)!";
				}
								 
				return "";
			}
		}
}
   