//------------------------------------------------------------------------------
//  <auto-generated>
//  此代码由模板自动生成
//  文件名称:TbUser.cs
//  生成时间: 2016-12-29 14:09:42 by dlm
//  对此文件的更改可能会导致不正确的行为，并且如果
//  重新生成代码，这些更改将会丢失
//  </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq; 
using System.Text;
namespace Gozyy.ToolClass.Models 
{
        [Gozyy.Repositories.TableName("TbUser")]
														
        public partial class TbUser
        {
            
		    /// <summary>
		    /// 
		    /// </summary>		
								    public int ID { get; set; }
					    
		    /// <summary>
		    /// 
		    /// </summary>		
						public string username { get; set; }
								    
		    /// <summary>
		    /// 
		    /// </summary>		
						public string password { get; set; }
								    
		    /// <summary>
		    /// 
		    /// </summary>		
						public string role { get; set; }
								    
		    /// <summary>
		    /// 
		    /// </summary>		
						public string loginip { get; set; }
								    
		    /// <summary>
		    /// 
		    /// </summary>		
						public string states { get; set; }
								     
        } 
		public partial class TbUserValid
		{
			public static string Check(TbUser m)
			{
																
				if(m.username!=null && m.username.Length>50)
				{
					return "username过长(50)!";
				}
												
				if(m.password!=null && m.password.Length>20)
				{
					return "password过长(20)!";
				}
												
				if(m.role!=null && m.role.Length>20)
				{
					return "role过长(20)!";
				}
												
				if(m.loginip!=null && m.loginip.Length>15)
				{
					return "loginip过长(15)!";
				}
												
				if(m.states!=null && m.states.Length>50)
				{
					return "states过长(50)!";
				}
								 
				return "";
			}
		}
}
   